### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bipol** [netanelgilad/angular-cesium#7]
Hey, could we add a license to this - just curious if I can fork it and add some features to the billboards that might alter how this entire thing works.

**Comment by netanelgilad** [comment]
Sure thing.. I've added MIT license.
If you prefer, I can just add you as a contributor with full permissions..
Have a great time @bipolalam!

**Comment by bipol** [comment]
@netanelgilad either works with me - whatever you'd prefer.  I'd just to add features like, auto-updating the positions on the billboards and labels and such.

Thanks for the license.

**Comment by netanelgilad** [comment]
Go ahead and fork it :)
I'm not maintaining it any way at the moment, and if you plan on maintaining it then it should be under your name :beers:

**Comment by bipol** [comment]
@netanelgilad sure, I'd love to be contributor!  Thanks Netanel. :beers:
